### ISSUE TITLE
New DCS Real Weather config may break compatibility with DCS Server Bot extension

### ISSUE THREAD

**Issue by evogelsa** [Special-K-s-Flightsim-Bots/DCSServerBot#28]
It appears the changes to Real Weather's configuration in v1.9.0-rc2 break compatibility with the DCS Server Bot extension. The new configuration file uses nested keys to improve readability in addition to adding more possible configuration options.

I believe the offending lines are the following from extensions/realweather.py

```py
cfg['input-mission-file'] = filename + '.orig'
cfg['output-mission-file'] = filename
for key in list(cfg.keys()):
    if key in self.config:
        cfg[key] = self.config[key]
```

**Comment by karel26** [comment]
The problem is you renamed the file keys... 
The result is, I now need to check which version of RW someone has and then implement two different versions of config files. 
The other option is that I just drop support for anything earlier than 1.9, which would be my preferred solution honestly as from what I've heard you've changed the mission writing with that version. I'll look at it later, but please never change parameters again for the sake of compatibility. Everyone that embeds your solution now has this issue.

**Comment by karel26** [comment]
I just dropped another version of DCSSB that addresses the changed config files.

**Comment by evogelsa** [comment]
> but please never change parameters again for the sake of compatibility

This is a pretty shallow and entitled take IMO... if you want compatibility use the native config 🤷

Alternatively I could look into adding support for command-line arguments or some other API more robust  than rewriting a config file by key name. I'd be happy to look into whatever solution you prefer. Feel free to open an issue, but maybe lose the attitude first. We all have the same goals to make DCS more enjoyable.

Thanks for the speedy fix.
